version: '3.8'

services:

  process:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
# simplicity sake chose sqlite, embedded so shared volume
#  db:
#    image: nouchka/sqlite3:latest
#    stdin_open: true
#    tty: true
#    ports:
#      - 80:80
#    volumes:
#      - .:/
